-------------------------------------------------------------------------------
Test set: com.luizalebs.comunicacao_api.business.ComunicacaoServiceTest
-------------------------------------------------------------------------------
Tests run: 18, Failures: 3, Errors: 3, Skipped: 0, Time elapsed: 0.19 s <<< FAILURE! - in com.luizalebs.comunicacao_api.business.ComunicacaoServiceTest
deveGerarExcecao_QuandoFalharAoSalvar_AgendarComunicacao2  Time elapsed: 0.014 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Unexpected exception type thrown, expected: <com.luizalebs.comunicacao_api.infraestructure.exceptions.BusinessException> but was: <com.luizalebs.comunicacao_api.infraestructure.exceptions.ConflictException>
	at com.luizalebs.comunicacao_api.business.ComunicacaoServiceTest.deveGerarExcecao_QuandoFalharAoSalvar_AgendarComunicacao2(ComunicacaoServiceTest.java:238)
Caused by: com.luizalebs.comunicacao_api.infraestructure.exceptions.ConflictException: Excecao
	at com.luizalebs.comunicacao_api.business.ComunicacaoServiceTest.lambda$deveGerarExcecao_QuandoFalharAoSalvar_AgendarComunicacao2$9(ComunicacaoServiceTest.java:238)
	at com.luizalebs.comunicacao_api.business.ComunicacaoServiceTest.deveGerarExcecao_QuandoFalharAoSalvar_AgendarComunicacao2(ComunicacaoServiceTest.java:238)

geraExcecao_QuandoBuscarStatusComunicacao2_NaoEncontrado  Time elapsed: 0.003 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Unexpected exception type thrown, expected: <com.luizalebs.comunicacao_api.infraestructure.exceptions.ResourceNotFoundException> but was: <java.lang.NullPointerException>
	at com.luizalebs.comunicacao_api.business.ComunicacaoServiceTest.geraExcecao_QuandoBuscarStatusComunicacao2_NaoEncontrado(ComunicacaoServiceTest.java:134)
Caused by: java.lang.NullPointerException: Cannot invoke "com.luizalebs.comunicacao_api.infraestructure.entities.ComunicacaoEntity.getEmailDestinatario()" because "entity" is null
	at com.luizalebs.comunicacao_api.business.ComunicacaoServiceTest.lambda$geraExcecao_QuandoBuscarStatusComunicacao2_NaoEncontrado$3(ComunicacaoServiceTest.java:134)
	at com.luizalebs.comunicacao_api.business.ComunicacaoServiceTest.geraExcecao_QuandoBuscarStatusComunicacao2_NaoEncontrado(ComunicacaoServiceTest.java:134)

geraExcecao_Quando_AgendarComunicacaoProjetoOriginal_SeDtoNull  Time elapsed: 0.002 s  <<< ERROR!
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because the return value of "java.lang.RuntimeException.getCause()" is null
	at com.luizalebs.comunicacao_api.business.ComunicacaoServiceTest.geraExcecao_Quando_AgendarComunicacaoProjetoOriginal_SeDtoNull(ComunicacaoServiceTest.java:191)

geraExcecao_QuandoAgendarComunicacao2_SeDtoNull  Time elapsed: 0.002 s  <<< ERROR!
java.lang.NullPointerException: Cannot invoke "java.lang.Throwable.getMessage()" because the return value of "java.lang.Throwable.getCause()" is null
	at com.luizalebs.comunicacao_api.business.ComunicacaoServiceTest.geraExcecao_QuandoAgendarComunicacao2_SeDtoNull(ComunicacaoServiceTest.java:253)

geraExcecao_Quando_AlterarStatusComunicacao  Time elapsed: 0.002 s  <<< ERROR!
java.lang.NullPointerException: Cannot invoke "java.lang.Throwable.getMessage()" because the return value of "com.luizalebs.comunicacao_api.infraestructure.exceptions.ResourceNotFoundException.getCause()" is null
	at com.luizalebs.comunicacao_api.business.ComunicacaoServiceTest.geraExcecao_Quando_AlterarStatusComunicacao(ComunicacaoServiceTest.java:149)

gerarExcecao_Quando_alterarStatsuComunicacao2  Time elapsed: 0.014 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Unexpected exception type thrown, expected: <com.luizalebs.comunicacao_api.infraestructure.exceptions.ResourceNotFoundException> but was: <org.mockito.exceptions.misusing.PotentialStubbingProblem>
	at com.luizalebs.comunicacao_api.business.ComunicacaoServiceTest.gerarExcecao_Quando_alterarStatsuComunicacao2(ComunicacaoServiceTest.java:159)
Caused by: org.mockito.exceptions.misusing.PotentialStubbingProblem: 

Strict stubbing argument mismatch. Please check:
 - this invocation of 'findByEmailDestinatario' method:
    comunicacaoRepository.findByEmailDestinatario(
    null
);
    -> at com.luizalebs.comunicacao_api.business.ComunicacaoService.alterarStatusComunicacao(ComunicacaoService.java:108)
 - has following stubbing(s) with different arguments:
    1. comunicacaoRepository.findByEmailDestinatario(
    "mensagem@email.com"
);
      -> at com.luizalebs.comunicacao_api.business.ComunicacaoServiceTest.gerarExcecao_Quando_alterarStatsuComunicacao2(ComunicacaoServiceTest.java:158)
Typically, stubbing argument mismatch indicates user mistake when writing tests.
Mockito fails early so that you can debug potential problem easily.
However, there are legit scenarios when this exception generates false negative signal:
  - stubbing the same method multiple times using 'given().will()' or 'when().then()' API
    Please use 'will().given()' or 'doReturn().when()' API for stubbing.
  - stubbed method is intentionally invoked with different arguments by code under test
    Please use default or 'silent' JUnit Rule (equivalent of Strictness.LENIENT).
For more information see javadoc for PotentialStubbingProblem class.
	at com.luizalebs.comunicacao_api.business.ComunicacaoServiceTest.lambda$gerarExcecao_Quando_alterarStatsuComunicacao2$5(ComunicacaoServiceTest.java:160)
	at com.luizalebs.comunicacao_api.business.ComunicacaoServiceTest.gerarExcecao_Quando_alterarStatsuComunicacao2(ComunicacaoServiceTest.java:159)

